/**
 * Alerion AI — Machine Telemetry & Prediction Types
 *
 * Central type definitions for the entire distributed pipeline:
 * Edge Nodes → Kafka → ML Inference → WebSocket → Dashboard
 */

// ─────────────────────────────────────────────────────────────
// Machine Telemetry (Edge → Kafka)
// ─────────────────────────────────────────────────────────────

/** Machine classification by operational capacity */
export type MachineType = 'L' | 'M' | 'H'; // Low, Medium, High

/** Failure modes detected by the ML model */
export type FailureType =
    | 'No Failure'
    | 'Heat Dissipation Failure'
    | 'Power Failure'
    | 'Overstrain Failure'
    | 'Tool Wear Failure'
    | 'Random Failures';

/**
 * Raw telemetry payload generated by edge nodes.
 * Matches the predictive_maintenance.csv schema.
 */
export interface MachineData {
    machine_id: string;
    machine_type: MachineType;
    air_temperature: number;    // Kelvin, range: 290–320
    process_temperature: number; // Kelvin, range: 300–340
    rotational_speed: number;    // RPM, range: 1000–3000
    torque: number;              // Nm, range: 10–80
    tool_wear: number;           // minutes, range: 0–250
    timestamp: string;           // ISO 8601
}

// ─────────────────────────────────────────────────────────────
// ML Prediction Output (ML Service → Kafka)
// ─────────────────────────────────────────────────────────────

/** Result from the ML inference layer, enriching raw telemetry */
export interface PredictionResult extends MachineData {
    prediction: 0 | 1;          // 0 = normal, 1 = failure predicted
    confidence: number;          // 0.0–1.0, model confidence score
    anomalyScore: number;        // 0.0–1.0, composite anomaly metric
    failure_type: FailureType;
    processed_at: string;        // ISO 8601 timestamp of inference
}

// ─────────────────────────────────────────────────────────────
// Edge Node Configuration
// ─────────────────────────────────────────────────────────────

/** Configuration for an individual edge node simulator */
export interface EdgeNodeConfig {
    machineId: string;
    machineType: MachineType;
    /** Telemetry send interval in milliseconds (default: 500) */
    intervalMs: number;
    /** Optional variance multiplier for sensor drift simulation */
    varianceFactor?: number;
}

// ─────────────────────────────────────────────────────────────
// Telemetry Generation Bounds
// ─────────────────────────────────────────────────────────────

/** Realistic operational bounds for telemetry generation */
export interface TelemetryBounds {
    airTemperature: { min: number; max: number };
    processTemperature: { min: number; max: number };
    rotationalSpeed: { min: number; max: number };
    torque: { min: number; max: number };
    toolWear: { min: number; max: number };
}

/** Default operational bounds matching the predictive_maintenance dataset */
export const DEFAULT_TELEMETRY_BOUNDS: TelemetryBounds = {
    airTemperature: { min: 290, max: 320 },
    processTemperature: { min: 300, max: 340 },
    rotationalSpeed: { min: 1000, max: 3000 },
    torque: { min: 10, max: 80 },
    toolWear: { min: 0, max: 250 },
};

// ─────────────────────────────────────────────────────────────
// WebSocket Message Envelope
// ─────────────────────────────────────────────────────────────

/** WebSocket message wrapper for frontend consumption */
export interface WSMessage<T = PredictionResult> {
    type: 'prediction' | 'alert' | 'heartbeat' | 'system';
    payload: T;
    timestamp: string;
}
